# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6f829e6484e942c472f765ef7882d508"
name = "AboutTheFit"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # GDPR Compliance Webhooks (Mandatory for App Store Distribution)
  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# read_products: Fetch product details and images for virtual try-on
# Note: App billing (appSubscriptionCreate) doesn't require explicit scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "/api/proxy"
subpath = "aboutthefit"
prefix = "apps"
